---
- name: Disable Swap
  shell: "swapoff -a"
- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present
- name: Add Keys
  apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    validate_certs: no
    state: present
- name: Add kubernetes Repositorys
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
    
- name: Install Basic Packets
  become: yes
  apt:
    name: "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker.io
    - apt-transport-https
    - kubectl
    - kubeadm
    - kubelet
- name: Configuring Docker
  shell:
         |
         systemctl enable docker.service
         systemctl restart docker.service
- name: Configuring kubelet 
  shell: |
    echo "Environment=\"KUBELET_EXTRA_ARGS=--node-ip=$(/sbin/ip -o -4 addr list eth1 | awk '{print $4}' | cut -d/ -f1)\"" >> /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    systemctl daemon-reload
    systemctl enable kubelet.service
    systemctl restart kubelet
