---
- hosts: cluster
  gather_facts: yes
  become: yes
  roles: 
    - { role: common, tags: common }
- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: master, tags: master}
    - { role: cni, tags: cni}
- hosts: node
  gather_facts: yes
  become: yes
  roles: 
    - { role: node, tags: node }
- hosts: master
  gather_facts: yes
  become: yes
  roles:
   - { role: istio, tags: istio}

